### ISSUE TITLE
bug in search

### ISSUE THREAD

**Issue by miland1990** [georgefeng/dynalist#1]
I found bug in searching. Every note will be in results) You should check substring of keyword in note)

**Comment by georgefeng** [comment]
Thanks for your issue, I will check and fix it soon.

**Comment by georgefeng** [comment]
[Addressed](https://github.com/georgefeng/dynalist/commit/058cd4556621da565a0cdad3f3097015b4645452) in this change.

Thanks again for reporting this!

**Comment by miland1990** [comment]
thank you) good work
